/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import logica.controladores.IControladorAlbum;
import logica.controladores.IControladorArtista;
import logica.controladores.IControladorCliente;
import logica.controladores.IControladorListaParticular;
import logica.controladores.IControladorListaPorDefecto;
import logica.controladores.IControladorTema;

/**
 *
 * @author Urbina
 */
public class AdministrarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form AdministrarUsuario
     */
    private IControladorCliente controlCli;
    private IControladorArtista controlArt;
    private IControladorTema controlTem;
    private IControladorAlbum controlAlb;
    private IControladorListaParticular controlListPar;
    private IControladorListaPorDefecto controlListPD;

    public AdministrarUsuario(IControladorCliente icc, IControladorArtista ica, IControladorTema ict, IControladorListaParticular iclp, IControladorListaPorDefecto icld, IControladorAlbum icalb) {
        controlCli = icc;
        controlArt = ica;
        controlTem = ict;
        controlAlb = icalb;
        controlListPar = iclp;        
        controlListPD = icld;
                
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlAU = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(872, 579));

        jPanel1.setPreferredSize(new java.awt.Dimension(872, 579));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pnlAU.setBackground(new java.awt.Color(255, 153, 153));
        pnlAU.setPreferredSize(new java.awt.Dimension(860, 471));

        javax.swing.GroupLayout pnlAULayout = new javax.swing.GroupLayout(pnlAU);
        pnlAU.setLayout(pnlAULayout);
        pnlAULayout.setHorizontalGroup(
            pnlAULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlAULayout.setVerticalGroup(
            pnlAULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPT", "Agregar Usuario", "Seguir Usuario", "Dejar de seguir Usuario", "Consultar Perfil de Usuario", "Eliminar Lista/Album/Tema de Fav", "Agregar Tema/Album/Lista a Fav" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlAU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        /*
                OPT
                Agregar Usuario
                Seguir Usuario
                Dejar de seguir Usuario
                Consultar Perfil de Usuario
                Eliminar Lista/Album/Tema de Fav
                Agregar Tema/Album/Lista a Fav
         */
        String token = String.valueOf(jComboBox1.getSelectedItem());

        switch (token) {
            case "OPT":
                //No
                pnlAU.removeAll();
                pnlAU.repaint();
                break;
            case "Agregar Usuario":

                AgregarUsuario au = new AgregarUsuario(controlCli, controlArt);
                au.setLocation(0, 0);
                au.setSize(860, 471);

                pnlAU.removeAll();
                pnlAU.add(au);
                pnlAU.revalidate();
                pnlAU.repaint();
                break;
            case "Seguir Usuario":

                SeguirUsuario su = new SeguirUsuario(controlCli);
                su.setLocation(0, 0);
                su.setSize(860, 471);

                pnlAU.removeAll();
                pnlAU.add(su);
                pnlAU.revalidate();
                pnlAU.repaint();
                break;

            case "Dejar de seguir Usuario":
                DejarDeSeguirUsuario ddsu = new DejarDeSeguirUsuario(controlCli);
                ddsu.setLocation(0, 0);
                ddsu.setSize(860, 471);

                pnlAU.removeAll();
                pnlAU.add(ddsu);
                pnlAU.revalidate();
                pnlAU.repaint();
                break;
            case "Consultar Perfil de Usuario":
                ConsultarPerfilDeUsuario cpdu = new ConsultarPerfilDeUsuario(controlCli, controlArt);
                cpdu.setLocation(0, 0);
                cpdu.setSize(860, 471);

                pnlAU.removeAll();
                pnlAU.add(cpdu);
                pnlAU.revalidate();
                pnlAU.repaint();
                break;
            case "Eliminar Lista/Album/Tema de Fav":
                EliminarCosoFav ecf = new EliminarCosoFav();
                ecf.setLocation(0, 0);
                ecf.setSize(860, 471);

                pnlAU.removeAll();
                pnlAU.add(ecf);
                pnlAU.revalidate();
                pnlAU.repaint();
                break;
            case "Agregar Tema/Album/Lista a Fav":
                AgregarCosoFav acf = new AgregarCosoFav(controlCli, controlTem, controlListPar, controlListPD, controlAlb);
                acf.setLocation(0, 0);
                acf.setSize(860, 471);

                pnlAU.removeAll();
                pnlAU.add(acf);
                pnlAU.revalidate();
                pnlAU.repaint();
                break;

            default:

                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlAU;
    // End of variables declaration//GEN-END:variables
}
