package presentacion;

import logica.controladores.IControladorAlbum;
import logica.controladores.IControladorArtista;
import logica.controladores.IControladorGenero;
import logica.controladores.IControladorTema;

public class AdministrarAlbum extends javax.swing.JPanel {

    private final IControladorAlbum controlAlb;
    private final IControladorGenero controlGen;
    private final IControladorTema controlTem;
    private final IControladorArtista controlArt;

    public AdministrarAlbum(IControladorAlbum icalb, IControladorGenero icg, IControladorTema ict, IControladorArtista ica) {
        controlAlb = icalb;
        controlGen = icg;
        controlTem = ict;
        controlArt = ica;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxOPT = new javax.swing.JComboBox<>();
        pnlAdAl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(872, 579));

        cbxOPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPT", "Agregar Album", "Consultar Album" }));
        cbxOPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOPTActionPerformed(evt);
            }
        });

        pnlAdAl.setBackground(new java.awt.Color(204, 204, 204));
        pnlAdAl.setPreferredSize(new java.awt.Dimension(860, 471));

        javax.swing.GroupLayout pnlAdAlLayout = new javax.swing.GroupLayout(pnlAdAl);
        pnlAdAl.setLayout(pnlAdAlLayout);
        pnlAdAlLayout.setHorizontalGroup(
            pnlAdAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlAdAlLayout.setVerticalGroup(
            pnlAdAlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jLabel1.setText("Operaciones de Album : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAdAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxOPT, 0, 240, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxOPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlAdAl, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxOPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOPTActionPerformed
        String token = String.valueOf(cbxOPT.getSelectedItem());
        switch (token) {
            case "OPT" -> {
                pnlAdAl.removeAll();
                pnlAdAl.revalidate();
                pnlAdAl.repaint();
            }
            case "Agregar Album" -> {
                AltaDeAlbum ada = new AltaDeAlbum(controlAlb, controlGen, controlTem, controlArt);
                ada.setLocation(0, 0);
                ada.setSize(860, 471);

                pnlAdAl.removeAll();
                pnlAdAl.add(ada);
                pnlAdAl.revalidate();
                pnlAdAl.repaint();
            }
            case "Consultar Album" -> {
                ConsultaDeAlbum cda = new ConsultaDeAlbum(controlAlb, controlArt, controlGen, controlTem);
                cda.setLocation(0, 0);
                cda.setSize(860, 471);

                pnlAdAl.removeAll();
                pnlAdAl.add(cda);
                pnlAdAl.revalidate();
                pnlAdAl.repaint();
            }
            default ->
                cbxOPT.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cbxOPTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxOPT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlAdAl;
    // End of variables declaration//GEN-END:variables
}
