/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import logica.controladores.IControladorListaParticular;
import logica.controladores.IControladorListaPorDefecto;

/**
 *
 * @author Urbina
 */

public class AdministrarLista extends javax.swing.JPanel {

    /**
     * Creates new form AdministrarUsuario
     */
    private IControladorListaParticular controlListPart;
    private IControladorListaPorDefecto controlListPD;
    public AdministrarLista(IControladorListaPorDefecto iclpd, IControladorListaParticular iclp) {
        initComponents();
        
        
        controlListPart = iclp;
        controlListPD = iclpd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAL = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbxOPT = new javax.swing.JComboBox<>();
        pnlAU1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(872, 579));

        pnlAL.setBackground(new java.awt.Color(153, 153, 255));
        pnlAL.setPreferredSize(new java.awt.Dimension(860, 471));

        javax.swing.GroupLayout pnlALLayout = new javax.swing.GroupLayout(pnlAL);
        pnlAL.setLayout(pnlALLayout);
        pnlALLayout.setHorizontalGroup(
            pnlALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlALLayout.setVerticalGroup(
            pnlALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(872, 579));

        cbxOPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPT", "Publicar Lista", " " }));
        cbxOPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOPTActionPerformed(evt);
            }
        });

        pnlAU1.setBackground(new java.awt.Color(255, 153, 153));
        pnlAU1.setPreferredSize(new java.awt.Dimension(860, 471));

        javax.swing.GroupLayout pnlAU1Layout = new javax.swing.GroupLayout(pnlAU1);
        pnlAU1.setLayout(pnlAU1Layout);
        pnlAU1Layout.setHorizontalGroup(
            pnlAU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlAU1Layout.setVerticalGroup(
            pnlAU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAU1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxOPT, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(cbxOPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlAU1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(pnlAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxOPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOPTActionPerformed
        int token = cbxOPT.getSelectedIndex();
        String tokenx = String.valueOf(cbxOPT.getSelectedItem());

        if (tokenx == "OPT"){
            pnlAL.removeAll();
            pnlAL.repaint();
        }else if (tokenx == "Publicar Lista"){
            PublicarLista pl = new PublicarLista(controlListPD,controlListPart );
            pl.setLocation(0,0);
            pl.setSize(860, 471);

            pnlAL.removeAll();
            pnlAL.add(pl);
            pnlAL.revalidate();
            pnlAL.repaint();
        }else{
            cbxOPT.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cbxOPTActionPerformed
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxOPT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlAL;
    private javax.swing.JPanel pnlAU1;
    // End of variables declaration//GEN-END:variables
}
