package presentacion;

import logica.controladores.IControladorAlbum;
import logica.controladores.IControladorCliente;
import logica.controladores.IControladorGenero;
import logica.controladores.IControladorListaParticular;
import logica.controladores.IControladorListaPorDefecto;
import logica.controladores.IControladorTema;

public class AdministrarLista extends javax.swing.JPanel {

    private final IControladorListaParticular controlListPart;
    private final IControladorListaPorDefecto controlListPD;
    private final IControladorGenero controlGen;
    private final IControladorCliente controlCli;
    private final IControladorTema controlTem;
    private final IControladorAlbum controlAlb;

    public AdministrarLista(IControladorListaPorDefecto iclpd, IControladorListaParticular iclp, IControladorCliente iclc, IControladorGenero icg, IControladorTema ict, IControladorAlbum ilb) {
        controlGen = icg;
        controlListPart = iclp;
        controlListPD = iclpd;
        controlCli = iclc;
        controlTem = ict;
        controlAlb = ilb;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAL = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbxOPT = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(872, 579));

        pnlAL.setBackground(new java.awt.Color(204, 204, 204));
        pnlAL.setPreferredSize(new java.awt.Dimension(860, 471));

        javax.swing.GroupLayout pnlALLayout = new javax.swing.GroupLayout(pnlAL);
        pnlAL.setLayout(pnlALLayout);
        pnlALLayout.setHorizontalGroup(
            pnlALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlALLayout.setVerticalGroup(
            pnlALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(872, 579));

        cbxOPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPT", "Crear Lista", "Publicar Lista", "Consultar Lista", "Agregar Tema a Lista", "Eliminar Tema De Lista" }));
        cbxOPT.setMaximumSize(new java.awt.Dimension(117, 26));
        cbxOPT.setMinimumSize(new java.awt.Dimension(117, 26));
        cbxOPT.setPreferredSize(new java.awt.Dimension(117, 26));
        cbxOPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOPTActionPerformed(evt);
            }
        });

        jLabel1.setText("Operaciones de Lista : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxOPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxOPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(510, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(pnlAL, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxOPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOPTActionPerformed
        String tokenx = String.valueOf(cbxOPT.getSelectedItem());
        switch (tokenx) {
            case "OPT" -> {
                pnlAL.removeAll();
                pnlAL.repaint();
            }
            case "Crear Lista" -> {
                AgregarListaDeReproduccion al = new AgregarListaDeReproduccion(controlCli, controlGen, controlListPart, controlListPD);
                al.setLocation(0, 0);
                al.setSize(860, 471);
                pnlAL.removeAll();
                pnlAL.add(al);
                pnlAL.revalidate();
                pnlAL.repaint();
            }
            case "Publicar Lista" -> {
                PublicarLista pl = new PublicarLista(controlListPD, controlListPart, controlCli);
                pl.setLocation(0, 0);
                pl.setSize(860, 471);
                pnlAL.removeAll();
                pnlAL.add(pl);
                pnlAL.revalidate();
                pnlAL.repaint();
            }
            case "Consultar Lista" -> {
                ConsultarLista cl = new ConsultarLista(controlGen, controlCli, controlListPart, controlListPD, controlTem);
                cl.setLocation(0, 0);
                cl.setSize(860, 471);
                pnlAL.removeAll();
                pnlAL.add(cl);
                pnlAL.revalidate();
                pnlAL.repaint();
            }
            case "Agregar Tema a Lista" -> {
                AgregarTemaALista al = new AgregarTemaALista(controlCli, controlListPart, controlListPD, controlTem, controlAlb);
                al.setLocation(0, 0);
                al.setSize(860, 471);
                pnlAL.removeAll();
                pnlAL.add(al);
                pnlAL.revalidate();
                pnlAL.repaint();
            }
            case "Eliminar Tema De Lista" -> {
                EliminarTemaDeLista el = new EliminarTemaDeLista(controlCli, controlListPart, controlListPD, controlTem, controlAlb);
                el.setLocation(0, 0);
                el.setSize(860, 471);
                pnlAL.removeAll();
                pnlAL.add(el);
                pnlAL.revalidate();
                pnlAL.repaint();
            }
            default ->
                cbxOPT.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cbxOPTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxOPT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlAL;
    // End of variables declaration//GEN-END:variables
}
