/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import logica.controladores.IControladorCliente;
import logica.controladores.IControladorArtista;

/**
 *
 * @author Urbina
 */
public class AgregarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form AgregarUsuario
     */
    private IControladorCliente controlCli;
    private IControladorArtista controlArt;
    public AgregarUsuario(IControladorCliente icc, IControladorArtista ica) {
        controlCli = icc;
        controlArt = ica;
        
        ica.agregarArtista("Pepe122", "Pepe", "Cuenca", "pepe@gmail.com", "dirFoto", LocalDate.of(2024,5,2), "Me gusta tocar la viola", "pepito.com");
        ica.agregarArtista("joselito", "Pepe", "Cuenca", "pepe@gmail.com", "dirFoto", LocalDate.of(2024,5,2), "Me gusta tocar la viola", "pepito.com");
        icc.agregarCliente("mario34", "Mario", "Fuentes", "mariofuentes@gmail.com", "dirFoto" , LocalDate.of(2002, 3, 1));
        icc.agregarCliente("El listo", "Larry", "Capaja", "larricapaja@gaymail.com", "defoult" , LocalDate.of(1969, 6, 9));
        
        
        initComponents();
        txtNull.setVisible(false);
         lblDirWeb.setVisible(false);
               txtDirWeb.setVisible(false);
               txtaBio.setVisible(false);
               lblBiografia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sprFecha = new javax.swing.JSpinner();
        lblFechaNaci = new javax.swing.JLabel();
        txtNickName = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        cbxTipoUsr = new javax.swing.JComboBox<>();
        lblBiografia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaBio = new javax.swing.JTextArea();
        lblDirWeb = new javax.swing.JLabel();
        txtDirWeb = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        lblIMGG = new javax.swing.JLabel();
        txtIMG = new javax.swing.JTextField();
        txtNull = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(860, 471));

        jLabel1.setText("NickName");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Correo");

        sprFecha.setModel(new javax.swing.SpinnerDateModel());
        sprFecha.setEditor(new javax.swing.JSpinner.DateEditor(sprFecha, "dd.MM.yyyy"));

        lblFechaNaci.setText("Fecha Naci");

        txtNickName.setColumns(10);
        txtNickName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNickNameActionPerformed(evt);
            }
        });

        txtNombre.setColumns(10);

        txtApellido.setColumns(10);

        txtCorreo.setColumns(10);

        cbxTipoUsr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPT", "Cliente", "Artista" }));
        cbxTipoUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoUsrActionPerformed(evt);
            }
        });

        lblBiografia.setText("Biografia");

        txtaBio.setColumns(20);
        txtaBio.setRows(5);
        jScrollPane1.setViewportView(txtaBio);

        lblDirWeb.setText("Direccion Web");

        txtDirWeb.setColumns(10);

        btnConfirmar.setText("OK");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblIMGG.setText("url Imagen de perfil");

        txtIMG.setColumns(10);

        txtNull.setColumns(10);
        txtNull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaNaci)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sprFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBiografia)
                            .addComponent(cbxTipoUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblDirWeb))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIMGG)
                                .addGap(21, 21, 21)
                                .addComponent(txtIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(txtDirWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)))
                .addGap(81, 81, 81)
                .addComponent(txtNull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(cbxTipoUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sprFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNaci)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblBiografia)
                                .addGap(56, 56, 56)
                                .addComponent(txtNull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIMGG)
                    .addComponent(txtIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDirWeb)
                    .addComponent(txtDirWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        
        
        if(cbxTipoUsr.getSelectedIndex() == 0){
            System.out.println("No opt elegida");
        }else{
             String pattern = "MM/dd/yyyy";

            DateFormat df = new SimpleDateFormat(pattern);

        
            Date today =(Date) sprFecha.getValue();        

            String fechaString = df.format(today);

            System.out.println("Today is: " + fechaString);

            DateTimeFormatter formatter
                = DateTimeFormatter.ofPattern("MM/dd/yyyy");
 

            LocalDate fechaFinal
                = LocalDate.parse(fechaString, formatter);
 
            String nick = txtNickName.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String correo = txtCorreo.getText();
            String foto = "foto"; //DE MOMENTO
              System.out.println("Converted LocalDate: "  + fechaFinal);
            
            if(cbxTipoUsr.getSelectedIndex() == 2){
                String biografia = txtaBio.getText();
                String webPag = txtDirWeb.getText();
                //deborlber cosas CON bio y web
                if(txtIMG.getText().isEmpty()){
                     controlArt.agregarArtista(nick, nombre, apellido, correo,"default", fechaFinal, biografia, webPag);
              
                }else{
                    controlArt.agregarArtista(nick, nombre, apellido, correo,txtIMG.getText(), fechaFinal, biografia, webPag);
                }
               
            }else{
                
                if(txtIMG.getText().isEmpty()){
                    
                     controlCli.agregarCliente(nick, nombre, apellido, correo,txtIMG.getText(), fechaFinal);
                }else{
                     controlCli.agregarCliente(nick, nombre, apellido, correo,"default", fechaFinal);
                }
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtNickNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNickNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNickNameActionPerformed

    private void cbxTipoUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoUsrActionPerformed
        int token = cbxTipoUsr.getSelectedIndex();
       
        switch (token) {
         case 0:
                 
               lblDirWeb.setVisible(false);
               txtDirWeb.setVisible(false);
               txtaBio.setVisible(false);
               lblBiografia.setVisible(false);
             
               
            case 1:
               lblDirWeb.setVisible(false);
               txtDirWeb.setVisible(false);
               txtaBio.setVisible(false);
               lblBiografia.setVisible(false);
             
             
                break;
            case 2:
               lblDirWeb.setVisible(true);
               txtDirWeb.setVisible(true);
               txtaBio.setVisible(true);
               lblBiografia.setVisible(true);
               
               
                break;    
    }//GEN-LAST:event_cbxTipoUsrActionPerformed
    }
    private void txtNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNullActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cbxTipoUsr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBiografia;
    private javax.swing.JLabel lblDirWeb;
    private javax.swing.JLabel lblFechaNaci;
    private javax.swing.JLabel lblIMGG;
    private javax.swing.JSpinner sprFecha;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDirWeb;
    private javax.swing.JTextField txtIMG;
    private javax.swing.JTextField txtNickName;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNull;
    private javax.swing.JTextArea txtaBio;
    // End of variables declaration//GEN-END:variables
}
