/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import logica.controladores.IControladorAlbum;
import logica.controladores.IControladorGenero;
import logica.controladores.IControladorTema;
import logica.dt.DataGenero;
import logica.dt.DataTema;
import com.mpatric.mp3agic.ID3v2;
import com.mpatric.mp3agic.Mp3File;
import logica.dt.DataAlbum;

/**
 *
 * @author Tabaré 8031
 */
public class AltaDeAlbum extends javax.swing.JPanel {
    
    /**
     * Creates new form AltaDeAlbum
     */
        private IControladorAlbum controlAlb;
        private IControladorGenero controlGen;
        private IControladorTema controlTem;
        private JFileChooser fileChooser;

    public AltaDeAlbum(IControladorAlbum ica, IControladorGenero icg, IControladorTema ict) {
        controlAlb = ica;
        controlGen = icg;
        controlTem = ict;
        fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Selecciona un archivo MP3");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos MP3", "mp3"));
        
        initComponents();
        cargarGeneros();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArt = new javax.swing.JLabel();
        txtArt = new javax.swing.JTextField();
        lblNomAlb = new javax.swing.JLabel();
        txtNomAlb = new javax.swing.JTextField();
        lblAnioAlb = new javax.swing.JLabel();
        sprAnio = new javax.swing.JSpinner();
        lblGenAlb = new javax.swing.JLabel();
        txtGenAlb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listGen = new javax.swing.JList<>();
        lblGenAlb1 = new javax.swing.JLabel();
        lblNomTemaAlb = new javax.swing.JLabel();
        txtNomTemaAlb = new javax.swing.JTextField();
        lblDurTemaAlb = new javax.swing.JLabel();
        sprDurTemaAlb = new javax.swing.JSpinner();
        lblUbiTemaAlb = new javax.swing.JLabel();
        sprUbiTemaAlb = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblNomTemaAlb1 = new javax.swing.JLabel();
        cbxTipMus = new javax.swing.JComboBox<>();
        txtTipMus = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        lblMsjArch = new javax.swing.JLabel();
        btnArch = new javax.swing.JButton();
        btnConfTem = new javax.swing.JButton();
        txtLinkImg = new javax.swing.JTextField();
        btnCarGen = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(860, 471));

        lblArt.setText("Ingrese el artista que crea el album");

        lblNomAlb.setText("Ingrese el nombre del album");

        lblAnioAlb.setText("Ingrese el año del album");

        lblGenAlb.setText("Ingrese los generos del album");

        jScrollPane1.setViewportView(listGen);

        lblGenAlb1.setText("Inserte link de imagen (opcional)");

        lblNomTemaAlb.setText("Ingrese el nombre del tema ");

        txtNomTemaAlb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomTemaAlbActionPerformed(evt);
            }
        });

        lblDurTemaAlb.setText("Ingrese la duracion del tema");

        lblUbiTemaAlb.setText("Ingrese la posicion del tema");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tema 1", "Tema 2", "Tema 3", "Tema 4", "Tema 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jList1HierarchyChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        lblNomTemaAlb1.setText("Temas del album");

        cbxTipMus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Archivo musica", "Direccion musica" }));

        btnConfirmar.setText("Dar de Alta Album");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblMsjArch.setText("El archivo no se reconoce como un mp3");

        btnArch.setText("Subir Archivo");
        btnArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchActionPerformed(evt);
            }
        });

        btnConfTem.setText("Confirmar Tema");
        btnConfTem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfTemActionPerformed(evt);
            }
        });

        btnCarGen.setText("Cargar Generos");
        btnCarGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarGenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAnioAlb)
                                    .addComponent(lblGenAlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnCarGen)
                                        .addComponent(lblGenAlb)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sprAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGenAlb)
                                    .addComponent(txtLinkImg)
                                    .addComponent(jScrollPane1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblArt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtArt))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNomAlb)
                                    .addGap(39, 39, 39)
                                    .addComponent(txtNomAlb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMsjArch)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUbiTemaAlb)
                                .addComponent(cbxTipMus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnArch)
                                .addComponent(btnConfTem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(txtTipMus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(sprUbiTemaAlb, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(148, 148, 148))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDurTemaAlb)
                            .addGap(18, 18, 18)
                            .addComponent(sprDurTemaAlb, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomTemaAlb1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomTemaAlb)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomTemaAlb, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomTemaAlb)
                            .addComponent(txtNomTemaAlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDurTemaAlb)
                            .addComponent(sprDurTemaAlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUbiTemaAlb)
                            .addComponent(sprUbiTemaAlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxTipMus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipMus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnArch)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfTem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMsjArch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArt)
                            .addComponent(txtArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomTemaAlb1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomAlb)
                            .addComponent(txtNomAlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGenAlb1)
                            .addComponent(txtLinkImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnioAlb)
                            .addComponent(sprAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGenAlb)
                            .addComponent(txtGenAlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCarGen)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtNomTemaAlbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomTemaAlbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomTemaAlbActionPerformed

    private void jList1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jList1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1HierarchyChanged

    private void btnCarGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarGenActionPerformed
        
    }//GEN-LAST:event_btnCarGenActionPerformed

    private void btnConfTemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfTemActionPerformed
       String nombre_tema = txtNomTemaAlb.getText();
       if(cbxTipMus.getSelectedItem() == "Archivo musica"){
            File selectedFile = fileChooser.getSelectedFile();
            File destinationDir = new File("Espotify_grupo7\\espotify\\src\\main\\java\\temas");
    
            if (!destinationDir.exists()) {
                destinationDir.mkdirs(); // Crear la carpeta si no existe
            }
    
            // Crear el archivo de destino con el mismo nombre que el seleccionado
            File destinationFile = new File(destinationDir, selectedFile.getName());
    
            // Copiar el archivo al destino
            if (selectedFile.getName().endsWith(".mp3")) {
                try {
                // Extract duration from the MP3 file
                Mp3File mp3File = new Mp3File(selectedFile.getAbsolutePath());
                if (mp3File.hasId3v2Tag()) {
                    ID3v2 id3v2Tag = mp3File.getId3v2Tag();
                    long durationInSeconds = mp3File.getLengthInSeconds();
                    JOptionPane.showMessageDialog(lblMsjArch, "Tema agregado con exito");
                    controlTem.crearTemaDefault(nombre_tema, (int) durationInSeconds);
                    try {
                        Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                        System.out.println("Archivo guardado exitosamente en: " + destinationFile.getAbsolutePath());
                    } catch (IOException i) {
                        System.out.println("Error al guardar el archivo.");
                    }
                } else {
                    JOptionPane.showMessageDialog(lblMsjArch, "Un error ha ocurrido.");
                }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(lblMsjArch, "Error al leer el archivo MP3");
                }

            } else {
                JOptionPane.showMessageDialog(lblMsjArch, "Por favor, seleccione un archivo MP3");
            }
       }else{
           controlTem.crearTemaDefault(nombre_tema, 69); //CALCULO DE DURACIONES
       }
       
       // DENTRO DE ACA REINICIO DE CAMPOS PARA LOS TEMAS
       
       //
    }//GEN-LAST:event_btnConfTemActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String nick_artista = txtArt.getText();
        String nombre_album = txtNomAlb.getText();
        String imagen = txtLinkImg.getText();
        Integer año_album = sprAnio.getComponentCount();
        
        //// CALCULAR TEMAS
        Collection<DataGenero> generos = new ArrayList<>();
        generos.add(new DataGenero("ALREDEDOR DE ESTO BUCLEAR POR CADA GENERO ELEGIDO"));
        ////
        
        //// CALCULAR GENEROS SELECCIONADOS
        Collection<DataTema> temas = new ArrayList<>();
        temas.add(new DataTema("ALREDEDOR DE ESTO BUCLEAR POR CADA TEMA ELEGIDO", 100, 1));
        //// 
        
        if(txtLinkImg.getText().isEmpty()){
            controlAlb.agregarAlbum(nick_artista, nombre_album, "default", año_album, generos, temas);
        }else{
            controlAlb.agregarAlbum(nick_artista, nombre_album, imagen, año_album, generos, temas);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchActionPerformed
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            if (selectedFile.getName().endsWith(".mp3")) {
                lblMsjArch.setText("Archivo seleccionado: " + selectedFile.getName());  
            }else{
            lblMsjArch.setText("Archivo seleccionado no valido");
            }
        }
    }//GEN-LAST:event_btnArchActionPerformed
    
    public void cargarGeneros(){
        DefaultListModel<String> model = new DefaultListModel();
        Collection<String> retorno = controlGen.mostrarGeneros();
            if(retorno.isEmpty()){
                model.addElement("No hay generos");
            }else{
                Iterator<String> iterator = retorno.iterator();
                while (iterator.hasNext()) {
                    model.addElement(iterator.next());
                }
            }
        listGen.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArch;
    private javax.swing.JToggleButton btnCarGen;
    private javax.swing.JButton btnConfTem;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cbxTipMus;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnioAlb;
    private javax.swing.JLabel lblArt;
    private javax.swing.JLabel lblDurTemaAlb;
    private javax.swing.JLabel lblGenAlb;
    private javax.swing.JLabel lblGenAlb1;
    private javax.swing.JLabel lblMsjArch;
    private javax.swing.JLabel lblNomAlb;
    private javax.swing.JLabel lblNomTemaAlb;
    private javax.swing.JLabel lblNomTemaAlb1;
    private javax.swing.JLabel lblUbiTemaAlb;
    private javax.swing.JList<String> listGen;
    private javax.swing.JSpinner sprAnio;
    private javax.swing.JSpinner sprDurTemaAlb;
    private javax.swing.JSpinner sprUbiTemaAlb;
    private javax.swing.JTextField txtArt;
    private javax.swing.JTextField txtGenAlb;
    private javax.swing.JTextField txtLinkImg;
    private javax.swing.JTextField txtNomAlb;
    private javax.swing.JTextField txtNomTemaAlb;
    private javax.swing.JTextField txtTipMus;
    // End of variables declaration//GEN-END:variables
}
