package presentacion;

import java.util.Collection;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.controladores.IControladorCliente;
import logica.dt.DataCliente;

public class DejarDeSeguirUsuario extends javax.swing.JPanel {

    private IControladorCliente controlCli;

    public DejarDeSeguirUsuario(IControladorCliente controlador) {
        this.controlCli = controlador;
        initComponents();
        this.cargarClientesLst(controlCli.mostrarClientes());

        this.cargarUsuariosLst(controlCli.mostrarUsuarios());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCliente = new javax.swing.JLabel();
        lblUsuarioAdejarDeSeguir = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        txtUsuarioAdejarDeSeguir = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUsuarios = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList<>();
        lblCliente1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(860, 471));

        lblCliente.setText("Clientes :");

        lblUsuarioAdejarDeSeguir.setText("Usuario a dejar de seguir :");

        btnConfirmar.setText("OK");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        txtCliente.setColumns(10);

        txtUsuarioAdejarDeSeguir.setColumns(10);

        lstUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstUsuarios);

        lstClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lstClientes);

        lblCliente1.setText("Cliente :");

        jLabel1.setText("Usuarios :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCliente1)
                            .addComponent(txtCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(lblUsuarioAdejarDeSeguir)
                            .addComponent(txtUsuarioAdejarDeSeguir))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCliente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(lblUsuarioAdejarDeSeguir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuarioAdejarDeSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String nickCliente = txtCliente.getText();
        String nickAseguir = txtUsuarioAdejarDeSeguir.getText();

        if (nickCliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa un nombre de usuario.");
        } else {

            DataCliente usr = controlCli.consultarPerfilCliente(nickCliente);
            if (usr != null) {
                DataCliente usr2 = controlCli.consultarPerfilCliente(nickCliente);
                if (usr2 != null) {

                    if (controlCli.corroborarSiEstaenSeguidos(nickCliente, nickAseguir) == true) {
                        controlCli.dejarDeSeguirUsuario(nickCliente, nickAseguir);
                        JOptionPane.showMessageDialog(null, "Seguimiento terminado con exito.");
                    } else {
                        JOptionPane.showMessageDialog(null, "El cliente " + txtCliente.getText() + " no esta siguiendo a " + txtUsuarioAdejarDeSeguir.getText());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario a seguir no encontrado");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado");
            }

        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    public void cargarClientesLst(Collection<DataCliente> cole) {
        DefaultListModel<String> model;

        model = new DefaultListModel<>();

        for (DataCliente elemento : cole) {
            String nick = elemento.getNickname();
            model.addElement(nick);
        }
        lstClientes.setModel(model);

    }

    public void cargarUsuariosLst(Collection<String> cole) {
        DefaultListModel<String> model;

        model = new DefaultListModel<>();

        for (String elemento : cole) {
            String nick = elemento;
            model.addElement(nick);
        }
        lstUsuarios.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblUsuarioAdejarDeSeguir;
    private javax.swing.JList<String> lstClientes;
    private javax.swing.JList<String> lstUsuarios;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtUsuarioAdejarDeSeguir;
    // End of variables declaration//GEN-END:variables
}
