/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import logica.controladores.IControladorAlbum;
import logica.controladores.IControladorArtista;
import logica.controladores.IControladorCliente;
import logica.controladores.IControladorGenero;
import logica.controladores.IControladorListaParticular;
import logica.controladores.IControladorListaPorDefecto;
import logica.controladores.IControladorTema;

/**
 *
 * @author Urbina
 */
public class FormPrin extends javax.swing.JFrame {

    /**
     * Creates new form FormPrin
     */
    private IControladorAlbum controlAlb;
    private IControladorGenero controlGen;
    private IControladorCliente controlCli;
    private IControladorArtista controlArt;
    private IControladorTema controlTem;
    
    private IControladorListaParticular controlListPar;
    private IControladorListaPorDefecto controlListPD;
    
    public FormPrin(IControladorListaParticular iclp,IControladorListaPorDefecto iclpd,IControladorCliente icc, IControladorArtista ica, IControladorAlbum icalb, IControladorGenero icg, IControladorTema ict) {
        controlCli = icc;
        controlArt = ica;
        controlAlb = icalb;
        controlGen = icg;
        controlTem = ict;
        controlListPD =iclpd;
        controlListPar =iclp;
                
                
                
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrin = new javax.swing.JPanel();
        btnAdLi = new javax.swing.JButton();
        btnAdAl = new javax.swing.JButton();
        btnAdUs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrin.setBackground(new java.awt.Color(153, 255, 204));
        pnlPrin.setPreferredSize(new java.awt.Dimension(872, 579));

        javax.swing.GroupLayout pnlPrinLayout = new javax.swing.GroupLayout(pnlPrin);
        pnlPrin.setLayout(pnlPrinLayout);
        pnlPrinLayout.setHorizontalGroup(
            pnlPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPrinLayout.setVerticalGroup(
            pnlPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        btnAdLi.setText("Administrar Lista");
        btnAdLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdLiActionPerformed(evt);
            }
        });

        btnAdAl.setText("Administar Album");
        btnAdAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdAlActionPerformed(evt);
            }
        });

        btnAdUs.setText("Administrar Usuario");
        btnAdUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdUsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAdUs, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdLi, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdAl, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(pnlPrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdUsActionPerformed
        
               AdministrarUsuario au = new  AdministrarUsuario(controlCli,controlArt,controlTem,controlListPar,controlListPD,controlAlb);
               au.setLocation(0,0);
               au.setSize(872, 579);
               
               pnlPrin.removeAll();
               pnlPrin.add(au);
               pnlPrin.revalidate();
               pnlPrin.repaint();
    
 
                
    }//GEN-LAST:event_btnAdUsActionPerformed

    private void btnAdAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdAlActionPerformed
      
        AdministrarAlbum aa = new AdministrarAlbum(controlAlb, controlGen, controlTem, controlArt);
               aa.setLocation(0,0);
               aa.setSize(872, 579);
               
               pnlPrin.removeAll();
               pnlPrin.add(aa);
               pnlPrin.revalidate();
               pnlPrin.repaint();
    }//GEN-LAST:event_btnAdAlActionPerformed

    private void btnAdLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdLiActionPerformed
         AdministrarLista aL = new AdministrarLista(controlListPD,controlListPar);
        aL.setLocation(0,0);
               aL.setSize(872, 579);
               
               pnlPrin.removeAll();
               pnlPrin.add(aL);
               pnlPrin.revalidate();
               pnlPrin.repaint();
    }//GEN-LAST:event_btnAdLiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdAl;
    private javax.swing.JButton btnAdLi;
    private javax.swing.JButton btnAdUs;
    private javax.swing.JPanel pnlPrin;
    // End of variables declaration//GEN-END:variables
}
