package presentacion;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JOptionPane;
import logica.controladores.*;
import logica.dt.DataCliente;
import logica.dt.DataGenero;
import logica.dt.DataListaPorDefecto;
import logica.factory.Fabrica;

public class FormPrin extends javax.swing.JFrame {

    private final IControladorAlbum controlAlb;
    private final IControladorGenero controlGen;
    private final IControladorCliente controlCli;
    private final IControladorArtista controlArt;
    private final IControladorTema controlTem;
    private final IControladorListaParticular controlListPar;
    private final IControladorListaPorDefecto controlListPD;

    public FormPrin() {

        Fabrica factory = Fabrica.getInstance();

        controlCli = factory.getIControladorCliente();
        controlArt = factory.getIControladorArtista();
        controlAlb = factory.getIControladorAlbum();
        controlGen = factory.getIControladorGenero();
        controlTem = factory.getIControladorTema();
        controlListPD = factory.getIControladorListaPorDefecto();
        controlListPar = factory.getIControladorListaParticular();

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrin = new javax.swing.JPanel();
        btnAdLi = new javax.swing.JButton();
        btnAdAl = new javax.swing.JButton();
        btnAdUs = new javax.swing.JButton();
        btnCarDat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Espotify");
        setResizable(false);

        pnlPrin.setBackground(new java.awt.Color(153, 255, 204));
        pnlPrin.setPreferredSize(new java.awt.Dimension(872, 579));

        javax.swing.GroupLayout pnlPrinLayout = new javax.swing.GroupLayout(pnlPrin);
        pnlPrin.setLayout(pnlPrinLayout);
        pnlPrinLayout.setHorizontalGroup(
            pnlPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPrinLayout.setVerticalGroup(
            pnlPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        btnAdLi.setText("Administrar Lista");
        btnAdLi.setPreferredSize(new java.awt.Dimension(210, 23));
        btnAdLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdLiActionPerformed(evt);
            }
        });

        btnAdAl.setText("Administar Album");
        btnAdAl.setPreferredSize(new java.awt.Dimension(210, 23));
        btnAdAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdAlActionPerformed(evt);
            }
        });

        btnAdUs.setText("Administrar Usuario");
        btnAdUs.setPreferredSize(new java.awt.Dimension(210, 23));
        btnAdUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdUsActionPerformed(evt);
            }
        });

        btnCarDat.setText("Cargar Datos");
        btnCarDat.setPreferredSize(new java.awt.Dimension(210, 23));
        btnCarDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarDatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAdUs, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdLi, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdAl, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarDat, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(pnlPrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdUsActionPerformed

        AdministrarUsuario au = new AdministrarUsuario(controlCli, controlArt, controlTem, controlListPar, controlListPD, controlAlb);
        au.setLocation(0, 0);
        au.setSize(872, 579);

        pnlPrin.removeAll();
        pnlPrin.add(au);
        pnlPrin.revalidate();
        pnlPrin.repaint();
    }//GEN-LAST:event_btnAdUsActionPerformed

    private void btnAdAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdAlActionPerformed

        AdministrarAlbum aa = new AdministrarAlbum(controlAlb, controlGen, controlTem, controlArt);
        aa.setLocation(0, 0);
        aa.setSize(872, 579);

        pnlPrin.removeAll();
        pnlPrin.add(aa);
        pnlPrin.revalidate();
        pnlPrin.repaint();
    }//GEN-LAST:event_btnAdAlActionPerformed

    private void btnAdLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdLiActionPerformed
        AdministrarLista aL = new AdministrarLista(controlListPD, controlListPar, controlCli, controlGen, controlTem);
        aL.setLocation(0, 0);
        aL.setSize(872, 579);

        pnlPrin.removeAll();
        pnlPrin.add(aL);
        pnlPrin.revalidate();
        pnlPrin.repaint();
    }//GEN-LAST:event_btnAdLiActionPerformed

    private void btnCarDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarDatActionPerformed

        try {
            cargarClientes();
            cargarArtistas();
            cargarGeneros();
            cargarTemas();
            cargarSeguimientos();
            cargarListas();

            JOptionPane.showMessageDialog(null, "Datos cargados correctamente.");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al cargar datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCarDatActionPerformed

    private void cargarGeneros() {

        Collection<String> subsPop = new ArrayList<>();
        subsPop.add("Electropop"); // EPO
        subsPop.add("Dance-pop"); // DPO
        subsPop.add("Pop Clásico"); // PCL

        Collection<String> subsRock = new ArrayList<>();
        subsRock.add("Rock Clásico"); // RCL
        subsRock.add("Rock Latino"); // RKL
        subsRock.add("Rock & Roll"); // RAR

        controlGen.crearGeneroUnico("Clásica"); // CLA
        controlGen.crearGeneroUnico("Disco"); // DIS
        controlGen.crearGeneroUnico("Balada"); // BAL
        controlGen.crearGeneroUnico("Cumbia"); // CUM

        controlGen.crearGeneroConSubgeneros("Rock", subsRock); // ROK
        controlGen.crearGeneroConSubgeneros("Pop", subsPop); // POP

        System.out.println("GENEROS CARGADOS");
    }

    private void cargarListas() {

        controlListPD.crearLista("Noche De La Nostalgia", new DataGenero("Pop Clásico"), "bit.ly/laNocheNostalgia"); // LD1
        controlListPD.crearLista("Rock En Español", new DataGenero("Rock Latino"), null); // LD2
        controlListPD.crearLista("Música Clásica", new DataGenero("Clásica"), "bit.ly/musicaCla"); // LD3

        DataListaPorDefecto lista = controlListPD.devolverInformacion("Noche De La Nostalgia", "Pop Clásico");
        lista.agregarTema(controlTem.retornarTema("YMCA"));
        lista.agregarTema(controlTem.retornarTema("Macho Man"));
        controlListPD.actualizarLista(lista);

        try {
            DataCliente VC = controlCli.consultarPerfilCliente("el_padrino");
            controlListPar.crearListaConVisibilidad("Música Inspiradora", VC, true, "bit.ly/musicInspi");

            DataCliente SO = controlCli.consultarPerfilCliente("scarlettO");
            controlListPar.crearListaConVisibilidad("De Todo Un Poco", SO, true, null);

            DataCliente WW = controlCli.consultarPerfilCliente("Heisenberg");
            controlListPar.crearListaConVisibilidad("Para Cocinaro", WW, false, "bit.ly/ParaCocinar");

            DataCliente ML = controlCli.consultarPerfilCliente("lachiqui");
            controlListPar.crearListaConVisibilidad("Para Las Chicas", ML, true, null);

            DataCliente CB = controlCli.consultarPerfilCliente("cbochinche");
            controlListPar.crearListaConVisibilidad("Fiesteras", CB, true, "bit.ly/fiestaFiesta");

            controlListPar.crearLista("Mis Favoritas", CB);

            System.out.println("LISTAS CARGADAS");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al cargar datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarTemas() {

        controlTem.crearTemaDefault("YMCA", 428, "mp3", "identificador archivo mp3");
        controlTem.crearTemaDefault("Macho Man", 328, "web", null);
        controlTem.crearTemaDefault("In the Navy", 313, "mp3", "identificador archivo mp3");
        System.out.println("LISTAS CARGADAS");
    }

    private void cargarSeguimientos() {

        controlCli.seguirUsuario("el_padrino", "vpeople");
        controlCli.seguirUsuario("el_padrino", "dmode");
        controlCli.seguirUsuario("el_padrino", "bruceTheBoss");
        controlCli.seguirUsuario("el_padrino", "benKenobi");
        controlCli.seguirUsuario("el_padrino", "lachiqui");
        controlCli.seguirUsuario("el_padrino", "cbochinche");
        controlCli.seguirUsuario("el_padrino", "Eleven11");

        controlCli.seguirUsuario("scarlettO", "dmode");
        controlCli.seguirUsuario("scarlettO", "bruceTheBoss");
        controlCli.seguirUsuario("scarlettO", "tigerOfWales");
        controlCli.seguirUsuario("scarlettO", "tripleNelson");
        controlCli.seguirUsuario("scarlettO", "Heisenberg");
        controlCli.seguirUsuario("scarlettO", "benKenobi");
        controlCli.seguirUsuario("scarlettO", "lachiqui");

        controlCli.seguirUsuario("ppArgento", "dmode");
        controlCli.seguirUsuario("ppArgento", "bruceTheBoss");
        controlCli.seguirUsuario("ppArgento", "tripleNelson");
        controlCli.seguirUsuario("ppArgento", "benKenobi");
        controlCli.seguirUsuario("ppArgento", "lachiqui");
        controlCli.seguirUsuario("ppArgento", "cbochinche");
        controlCli.seguirUsuario("ppArgento", "Eleven11");

        controlCli.seguirUsuario("Heisenberg", "dmode");
        controlCli.seguirUsuario("Heisenberg", "bruceTheBoss");
        controlCli.seguirUsuario("Heisenberg", "tigerOfWales");
        controlCli.seguirUsuario("Heisenberg", "tripleNelson");
        controlCli.seguirUsuario("Heisenberg", "lospimpi");
        controlCli.seguirUsuario("Heisenberg", "dyangounchained");
        controlCli.seguirUsuario("Heisenberg", "alcides");
        controlCli.seguirUsuario("Heisenberg", "el_padrino");
        controlCli.seguirUsuario("Heisenberg", "ppArgento");
        controlCli.seguirUsuario("Heisenberg", "benKenobi");
        controlCli.seguirUsuario("Heisenberg", "lachiqui");
        controlCli.seguirUsuario("Heisenberg", "Eleven11");

        controlCli.seguirUsuario("benKenobi", "dmode");
        controlCli.seguirUsuario("benKenobi", "bruceTheBoss");
        controlCli.seguirUsuario("benKenobi", "la_ley");
        controlCli.seguirUsuario("benKenobi", "chaiko");
        controlCli.seguirUsuario("benKenobi", "nicoleneu");
        controlCli.seguirUsuario("benKenobi", "lospimpi");
        controlCli.seguirUsuario("benKenobi", "alcides");
        controlCli.seguirUsuario("benKenobi", "el_padrino");
        controlCli.seguirUsuario("benKenobi", "ppArgento");
        controlCli.seguirUsuario("benKenobi", "lachiqui");
        controlCli.seguirUsuario("benKenobi", "cbochinche");
        controlCli.seguirUsuario("benKenobi", "Eleven11");

        controlCli.seguirUsuario("lachiqui", "bruceTheBoss");
        controlCli.seguirUsuario("lachiqui", "la_ley");
        controlCli.seguirUsuario("lachiqui", "lospimpi");
        controlCli.seguirUsuario("lachiqui", "alcides");
        controlCli.seguirUsuario("lachiqui", "el_padrino");
        controlCli.seguirUsuario("lachiqui", "scarlettO");
        controlCli.seguirUsuario("lachiqui", "ppArgento");

        controlCli.seguirUsuario("cbochinche", "la_ley");
        controlCli.seguirUsuario("cbochinche", "lospimpi");
        controlCli.seguirUsuario("cbochinche", "dyangounchained");
        controlCli.seguirUsuario("cbochinche", "alcides");
        controlCli.seguirUsuario("cbochinche", "ppArgento");

        controlCli.seguirUsuario("Eleven11", "la_ley");
        controlCli.seguirUsuario("Eleven11", "el_padrino");
        controlCli.seguirUsuario("Eleven11", "scarlettO");
        controlCli.seguirUsuario("Eleven11", "ppArgento");
    }

    private void cargarClientes() {
        //CLIENTES//
        controlCli.agregarCliente("Eleven11", "Eleven", "", "Eleven11@gmail.com", "bit.ly/11Eleven11", LocalDate.of(1971, 12, 31)); //EL
        controlCli.agregarCliente("cbochinche", "Cacho", "Bochinche", "cbochinche@vera.com.uy", "bit.ly/cbochinche", LocalDate.of(1937, 5, 8)); //CB
        controlCli.agregarCliente("lachiqui", "Mirtha", "Legrand", "lachiqui@hotmail.com.ar", "bit.ly/laChiqui", LocalDate.of(1927, 2, 3)); //ML
        controlCli.agregarCliente("benKenobi", "Obi-Wan", "Kenobi", "benKenobi@gmail.com", "bit.ly/benKenobi", LocalDate.of(1914, 4, 2)); //OK
        controlCli.agregarCliente("Heisenberg", "Walter", "White", "Heisenberg@tuta.io", "bit.ly/heisenbergWW", LocalDate.of(1956, 3, 7)); //WW
        controlCli.agregarCliente("ppArgento", "Pepe", "Argento", "ppArgento@hotmail.com", "bit.ly/ppArgento", LocalDate.of(1955, 2, 14)); //PA
        controlCli.agregarCliente("scarlettO", "Scarlett", "O’Hara", "scarlettO@tuta.io", "bit.ly/scarlettO", LocalDate.of(1984, 11, 27)); //SO
        controlCli.agregarCliente("el_padrino", "Vito", "Corleone", "el_padrino@tuta.io", "bit.ly/vitoCorleone", LocalDate.of(1972, 3, 8)); //VC
        //-------//
        System.out.println("CLIENTES CARGADOS");
    }

    private void cargarArtistas() {

        //ARTISTAS//
        controlArt.agregarArtista("vpeople", "Village", "People", "vpeople@tuta.io", "bit.ly/vpeople", LocalDate.of(1977, 1, 1), """
                                                                                                                                     Village People es una
                                                                                                                                     innovadora formaci\u00f3n musical
                                                                                                                                     de estilo disco de finales de los
                                                                                                                                     a\u00f1os 70. Fue famosa tanto por
                                                                                                                                     sus peculiares disfraces, como
                                                                                                                                     por sus canciones pegadizas,
                                                                                                                                     con letras sugerentes y llenas de
                                                                                                                                     dobles sentidos.""", "www.officialvillagepeople.com"); //VP

        controlArt.agregarArtista("dmode", "Depeche", "Mode", "dmode@tuta.io", "bit.ly/depecheMode", LocalDate.of(1980, 6, 14), "", "www.depechemode.com"); //DM

        controlArt.agregarArtista("clauper", "Cyndi", "Lauper", "clauper@hotmail.com", "bit.ly/cLauper", LocalDate.of(1953, 6, 22), """
                                                                                                                                        Cynthia Ann Stephanie Lauper,
                                                                                                                                        conocida simplemente como
                                                                                                                                        Cyndi Lauper, es una
                                                                                                                                        cantautora, actriz y empresaria
                                                                                                                                        estadounidense. Despu\u00e9s de
                                                                                                                                        participar en el grupo musical,
                                                                                                                                        Blue Angel, en 1983 firm\u00f3 con
                                                                                                                                        Portrait Records (filial de Epic
                                                                                                                                        Records) y lanz\u00f3 su exitoso
                                                                                                                                        \u00e1lbum debut She's So Unusual a
                                                                                                                                        finales de ese mismo a\u00f1o.
                                                                                                                                        Sigui\u00f3 lanzando una serie de
                                                                                                                                        \u00e1lbumes en los que encontr\u00f3
                                                                                                                                        una inmensa popularidad,
                                                                                                                                        superando los l\u00edmites de
                                                                                                                                        contenido de las letras de sus
                                                                                                                                        canciones.""", "cyndilauper.com"); //CL

        controlArt.agregarArtista("bruceTheBoss", "Bruce", "Springsteen", "bruceTheBoss@gmail.com", "bit.ly/bruceTheBoss", LocalDate.of(1949, 9, 23), "", "brucespringsteen.net"); //BS

        controlArt.agregarArtista("tripleNelson", "La", "Triple Nelson", "tripleNelson@tuta.io", "bit.ly/tripleNelson", LocalDate.of(1998, 1, 1), """
                                                                                                                                                      La Triple Nelson es un grupo
                                                                                                                                                      de rock uruguayo formado en
                                                                                                                                                      enero de 1998 e integrado
                                                                                                                                                      inicialmente por Christian Cary
                                                                                                                                                      (guitarra y voz), Fernando
                                                                                                                                                      "Paco" Pintos (bajo y coros) y
                                                                                                                                                      Rub\u00e9n Otonello (actualmente su
                                                                                                                                                      nuevo baterista es Rafael Ugo).""", ""); //TN

        controlArt.agregarArtista("la_ley", "La", "Ley", "la_ley@tuta.io", "", LocalDate.of(1987, 2, 14), "", ""); //LL

        controlArt.agregarArtista("tigerOfWales", "Tom", "Jones", "tigerOfWales@tuta.io", "", LocalDate.of(1940, 6, 7), """
                                                                                                                            Sir Thomas John, conocido por
                                                                                                                            su nombre art\u00edstico de Tom
                                                                                                                            Jones, es un cantante brit\u00e1nico.
                                                                                                                            Ha vendido m\u00e1s de 100
                                                                                                                            millones de discos en todo el
                                                                                                                            mundo.1""", "www.tomjones.com"); //TJ

        controlArt.agregarArtista("chaiko", "Piotr", "Tchaikovsky", "chaiko@tuta.io", "", LocalDate.of(1840, 4, 25), """
                                                                                                                         Piotr Ilich Chaikovski fue un
                                                                                                                         compositor ruso del per\u00edodo del
                                                                                                                         Romanticismo""", ""); //PT

        controlArt.agregarArtista("nicoleneu", "Nicole", "Neumann", "nicoleneu@hotmail.com", "bit.ly/nicoleneu", LocalDate.of(1980, 10, 31), "", ""); //NN

        controlArt.agregarArtista("lospimpi", "Pimpinela", "", "lospimpi@gmail.com", "bit.ly/losPimpinela", LocalDate.of(1981, 8, 13), "", "www.pimpinela.net"); //PI

        controlArt.agregarArtista("dyangounchained", "Dyango", "", "dyangounchained@gmail.com", "", LocalDate.of(1940, 3, 5), """
                                                                                                                                  Jos\u00e9 G\u00f3mez Romero, conocido
                                                                                                                                  art\u00edsticamente como Dyango es
                                                                                                                                  un cantante espa\u00f1ol de m\u00fasica
                                                                                                                                  rom\u00e1ntica.""", ""); //DY

        controlArt.agregarArtista("alcides", "", "Alcides", "alcides@tuta.io", "", LocalDate.of(1952, 7, 17), """
                                                                                                                  Su carrera comienza en 1976
                                                                                                                  cuando forma la banda Los
                                                                                                                  Playeros junto a su hermano V\u00edctor.
                                                                                                                  Al poco tiempo se
                                                                                                                  mudan a San Luis donde
                                                                                                                  comienzan a hacerse conocidos
                                                                                                                  en la escena musical. Su \u00e9xito a
                                                                                                                  nivel nacional llega a comienzos
                                                                                                                  de los a\u00f1os 1990 cuando
                                                                                                                  desembarca en Buenos Aires y
                                                                                                                  graba el \u00e9xito "Violeta",
                                                                                                                  originalmente compuesta e
                                                                                                                  interpretada en 1985 por el
                                                                                                                  m\u00fasico brasile\u00f1o Luiz Caldas
                                                                                                                  bajo el t\u00edtulo \u00abFricote\u00bb.""", ""); //AL
        //---------//
        System.out.println("ARTISTAS CARGADOS");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdAl;
    private javax.swing.JButton btnAdLi;
    private javax.swing.JButton btnAdUs;
    private javax.swing.JButton btnCarDat;
    private javax.swing.JPanel pnlPrin;
    // End of variables declaration//GEN-END:variables
}
