package presentacion;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JOptionPane;
import logica.controladores.*;
import logica.dt.DataGenero;
import logica.dt.DataListaPorDefecto;
import logica.factory.Fabrica;

public class FormPrin extends javax.swing.JFrame {

    private final IControladorAlbum controlAlb;
    private final IControladorGenero controlGen;
    private final IControladorCliente controlCli;
    private final IControladorArtista controlArt;
    private final IControladorTema controlTem;
    private final IControladorListaParticular controlListPar;
    private final IControladorListaPorDefecto controlListPD;

    public FormPrin() {

        Fabrica factory = Fabrica.getInstance();

        controlCli = factory.getIControladorCliente();
        controlArt = factory.getIControladorArtista();
        controlAlb = factory.getIControladorAlbum();
        controlGen = factory.getIControladorGenero();
        controlTem = factory.getIControladorTema();
        controlListPD = factory.getIControladorListaPorDefecto();
        controlListPar = factory.getIControladorListaParticular();

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrin = new javax.swing.JPanel();
        btnAdLi = new javax.swing.JButton();
        btnAdAl = new javax.swing.JButton();
        btnAdUs = new javax.swing.JButton();
        btnCarDat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Espotify");
        setResizable(false);

        pnlPrin.setBackground(new java.awt.Color(153, 255, 204));
        pnlPrin.setPreferredSize(new java.awt.Dimension(872, 579));

        javax.swing.GroupLayout pnlPrinLayout = new javax.swing.GroupLayout(pnlPrin);
        pnlPrin.setLayout(pnlPrinLayout);
        pnlPrinLayout.setHorizontalGroup(
            pnlPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPrinLayout.setVerticalGroup(
            pnlPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        btnAdLi.setText("Administrar Lista");
        btnAdLi.setPreferredSize(new java.awt.Dimension(210, 23));
        btnAdLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdLiActionPerformed(evt);
            }
        });

        btnAdAl.setText("Administar Album");
        btnAdAl.setPreferredSize(new java.awt.Dimension(210, 23));
        btnAdAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdAlActionPerformed(evt);
            }
        });

        btnAdUs.setText("Administrar Usuario");
        btnAdUs.setPreferredSize(new java.awt.Dimension(210, 23));
        btnAdUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdUsActionPerformed(evt);
            }
        });

        btnCarDat.setText("Cargar Datos");
        btnCarDat.setPreferredSize(new java.awt.Dimension(210, 23));
        btnCarDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarDatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAdUs, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdLi, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdAl, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarDat, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(pnlPrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdUsActionPerformed

        AdministrarUsuario au = new AdministrarUsuario(controlCli, controlArt, controlTem, controlListPar, controlListPD, controlAlb);
        au.setLocation(0, 0);
        au.setSize(872, 579);

        pnlPrin.removeAll();
        pnlPrin.add(au);
        pnlPrin.revalidate();
        pnlPrin.repaint();
    }//GEN-LAST:event_btnAdUsActionPerformed

    private void btnAdAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdAlActionPerformed

        AdministrarAlbum aa = new AdministrarAlbum(controlAlb, controlGen, controlTem, controlArt);
        aa.setLocation(0, 0);
        aa.setSize(872, 579);

        pnlPrin.removeAll();
        pnlPrin.add(aa);
        pnlPrin.revalidate();
        pnlPrin.repaint();
    }//GEN-LAST:event_btnAdAlActionPerformed

    private void btnAdLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdLiActionPerformed
        AdministrarLista aL = new AdministrarLista(controlListPD, controlListPar, controlCli);
        aL.setLocation(0, 0);
        aL.setSize(872, 579);

        pnlPrin.removeAll();
        pnlPrin.add(aL);
        pnlPrin.revalidate();
        pnlPrin.repaint();
    }//GEN-LAST:event_btnAdLiActionPerformed

    private void btnCarDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarDatActionPerformed

        try {

            //CLIENTES//
            controlCli.agregarCliente("Eleven11", "Eleven", "", "Eleven11@gmail.com", "bit.ly/11Eleven11", LocalDate.of(1971, 12, 31)); //EL
            controlCli.agregarCliente("cbochinche", "Cacho", "Bochinche", "cbochinche@vera.com.uy", "bit.ly/cbochinche", LocalDate.of(1937, 5, 8)); //CB
            controlCli.agregarCliente("lachiqui", "Mirtha", "Legrand", "lachiqui@hotmail.com.ar", "bit.ly/laChiqui", LocalDate.of(1927, 2, 3)); //ML
            controlCli.agregarCliente("benKenobi", "Obi-Wan", "Kenobi", "benKenobi@gmail.com", "bit.ly/benKenobi", LocalDate.of(1914, 4, 2)); //OK
            controlCli.agregarCliente("Heisenberg", "Walter", "White", "Heisenberg@tuta.io", "bit.ly/heisenbergWW", LocalDate.of(1956, 3, 7)); //WW
            controlCli.agregarCliente("ppArgento", "Pepe", "Argento", "ppArgento@hotmail.com", "bit.ly/ppArgento", LocalDate.of(1955, 2, 14)); //PA
            controlCli.agregarCliente("scarlettO", "Scarlett", "O’Hara", "scarlettO@tuta.io", "bit.ly/scarlettO", LocalDate.of(1984, 11, 27)); //SO
            controlCli.agregarCliente("el_padrino", "Vito", "Corleone", "el_padrino@tuta.io", "bit.ly/vitoCorleone", LocalDate.of(1972, 3, 8)); //VC
            //-------//

            //GENEROS//
            Collection<String> generos1 = new ArrayList<>();

            generos1.add("Electropop"); //EPO
            generos1.add("Dance-pop"); //DPO
            generos1.add("Pop Clásico"); //PCL

            Collection<String> generos2 = new ArrayList<>();

            generos2.add("Rock Clásico"); //RCL
            generos2.add("Rock Latino"); //RKL
            generos2.add("Rock & Roll"); //RAR

            controlGen.crearGeneroUnico("Clásica"); //CLA
            controlGen.crearGeneroUnico("Disco"); //DIS
            controlGen.crearGeneroUnico("Balada"); //BAL
            controlGen.crearGeneroUnico("Cumbia"); //CUM

            controlGen.crearGeneroConSubgeneros("Rock", generos2); //ROK
            controlGen.crearGeneroConSubgeneros("Pop", generos1); //POP
            //--------//

            //LISTAS DE REPRODUCCION//
            controlListPD.crearLista("Noche De La Nostalgia", new DataGenero("Pop Clásico")); //LD1
            controlListPD.crearLista("Rock En Español", new DataGenero("Rock Latino")); //LD2
            controlListPD.crearLista("Música Clásica", new DataGenero("Clásica")); //LD3

            // controlListPar.crearLista("Música Inspiradora", new DataCliente().setNickname("el_padrino")); //en progreso
            controlTem.crearTemaDefault("YMCA", 428, "mp3");
            controlTem.crearTemaDefault("Macho Man", 328, "web");
            controlTem.crearTemaDefault("In the Navy", 313, "mp3");
            
            DataListaPorDefecto lista = controlListPD.devolverInformacion("Noche De La Nostalgia", "Pop");
            
         //->>>>   lista.agregarTema?////

            //----------------------//
            JOptionPane.showMessageDialog(null, "Datos cargados correctamente.");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al agregar cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        //controlArt.agregarArtista("lachiqui", "Mirtha", "Legrand", "imgoingtoalice@gmai.com", "Defoult", LocalDate.of(1927, 2, 3), "Im going to Alice. I want to eat Alice. What is Alice? Im Alice too!", "wonderland@gmail.com");
        /*controlCli.seguirUsuario("El Listo", "Jose");
        controlCli.seguirUsuario("El Listo", "Jhon Black Soul");
        controlCli.seguirUsuario("Jose", "El Listo");*/

 /*Collection<DataTema> tem = new ArrayList<>();
        controlAlb.agregarAlbum("Jhon Black Soul", "Welcome to Wonderland", "Alice.png", 2020, tem);
        controlGen.crearGeneroUnico("Genero 1");
        controlGen.crearGeneroUnico("Genero 2");
        controlGen.crearGeneroUnico("Genero 3");*/
    }//GEN-LAST:event_btnCarDatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdAl;
    private javax.swing.JButton btnAdLi;
    private javax.swing.JButton btnAdUs;
    private javax.swing.JButton btnCarDat;
    private javax.swing.JPanel pnlPrin;
    // End of variables declaration//GEN-END:variables
}
