package presentacion;

import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.controladores.IControladorCliente;
import logica.dt.DataRegi;

public class ListarRegistro extends javax.swing.JPanel {
 
   
    private final IControladorCliente controlCli;
    public ListarRegistro( IControladorCliente icc ) {
        initComponents();
         controlCli = icc;
        cargarDatos();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblCoso = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(860, 471));

        lblCoso.setText("Registros:");

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "O.S", "Navegador", "Fecha", "Cliente", "IP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblCoso)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoso))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCoso;
    private javax.swing.JTable tblTabla;
    // End of variables declaration//GEN-END:variables
    


   private void cargarDatos(){
        controlCli.hiroshimaYnagasaki();
        Collection <DataRegi> cole = this.controlCli.retornarRegistros(); 
        
       DefaultTableModel model;  
       model = new DefaultTableModel(new String[] {"Id", "O.S", "Navegador", "Fecha", "Cliente", "IP"}, 0);
        if(cole == null || cole.isEmpty()){
            JOptionPane.showMessageDialog(null, "No hay Registros");
        }else{
            
        for(DataRegi coso: cole){
        model.addRow(new Object[]{String.valueOf(coso.getId()), coso.getOs(), coso.getNave(), String.valueOf(coso.getFecha()),coso.getUserNick(), coso.getIp()});  
        }
             tblTabla.setModel(model);
        }

   }
   
   
}
